# Performs check on each push in the package, to ensure code quality

name: 'Continuous Integration'

on:
  push

jobs:
  run-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install package
        run: npm install
      - name: Check typescript
        run: npm run lint:ts
      - name: Check eslint
        run: npm run lint
      - name: Check tests
        run: npm run test
